apiVersion: v1
kind: Service
metadata:
  name: {{.Values.nginx.service.name}}
  namespace: {{ .Values.nginx.namespace.name }}
spec:
  type:  {{ .Values.nginx.service.type }}
  ports:
    - port:  {{ .Values.nginx.service.port }}
      targetPort:  {{ .Values.nginx.service.targetPort }}
      nodePort:  {{ .Values.nginx.service.nodePort }}
  selector:
    server: {{ .Values.nginx.name }}